layout_spectrum: 0.06412953441031277
typography_spectrum: 0.2469587076921016
color:
  brandColors:
    - '#000000'
    - '#404040'
    - '#808080'
    - '#BFBFBF'
    - '#FFFFFF'
  brandStrength: 0.5512625880073756
  lightness: 0.38719118386507034
  saturation: 0.9442025315947831
  rhythmicContrast: 0.007425902644172311
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
name: MarkBurkett Cinematographer
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Cinematographer
purpose: []
