layout_spectrum: 0.05693993694148958
typography_spectrum: 0.7290380599442869
color:
  brandColors:
    - '#DDDCC5'
    - '#958976'
    - '#611427'
    - '#1D2326'
    - '#6A6A61'
  brandStrength: 0.506331343902275
  lightness: 0.09858050663024187
  saturation: 0.38845586869865656
  rhythmicContrast: 0.6542842539492995
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
name: MarkBurkett Cinematographer
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Cinematographer
purpose: []
