name: MarkBurkett Cinematographer
favicon: null
layout_spectrum: 0.9552398859523237
typography_spectrum: 0.7195627531036735
title: Cinematographer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.49600570322945714
  lightness: 0.8411659204866737
  saturation: 0.1349841991905123
  rhythmicContrast: 0.5253317300230265
purpose: []
